config:
  outputs: |
    [OUTPUT]
        Name        opentelemetry
        Match       *
        Host        my-opentelemetry-collector.observability.svc.cluster.local
        Port        4317
        Grpc        On