apiVersion: ://coreos.com
kind: PodMonitor
metadata:
  name: istio-proxies-monitor
  namespace: observability
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: security.istio.io/tlsMode
        operator: Exists
  podMetricsEndpoints:
    - path: /stats/prometheus
      port: http-monitoring
      interval: 15s
