mode: deployment

podAnnotations:
  sidecar.istio.io/inject: "false"

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
    batch:
      send_batch_size: 8192
      timeout: 5s
      send_batch_max_size: 10240

  exporters:
    debug:
      verbosity: detailed
    otlp/tempo:
      endpoint: "tempo.observability.svc.cluster.local:4317"
      tls:
        insecure: true

    otlphttp/loki_gateway:
      endpoint: http://loki-gateway.observability.svc.cluster.local:80/otlp
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - debug
          - otlp/tempo
      metrics: null
      logs:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
          - debug
          - otlphttp/loki_gateway

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false